import mongoose from 'mongoose'

const feeSchema = new mongoose.Schema({
  student: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  room: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Room',
    required: true
  },

  // Fee details:
  amount: {
    type: Number,
    required: true
  },
  feeType: {
    type: String,
    enum: [
      'hostel_fee',
      'mess_fee',
      'maintenance_fee',
      'security_deposit',
      'late_fee',
      'other'
    ],
    default: 'hostel_fee'
  },
  roomType: {
    type: String,
    enum: ['ac', 'non_ac'],
    default: 'non_ac'
  },

  // Period:
  month: {
    type: Number, // 1-12
    required: true
  },
  year: {
    type: Number,
    required: true
  },

  // Status:
  status: {
    type: String,
    enum: ['pending', 'paid', 'overdue', 'waived'],
    default: 'pending'
  },

  // Payment details:
  paidAt: {
    type: Date,
    default: null
  },
  paidAmount: {
    type: Number,
    default: 0
  },
  paymentMethod: {
    type: String,
    enum: ['cash', 'upi', 'bank_transfer', 'online'],
    default: null
  },
  transactionId: {
    type: String,
    default: null
  },

  // Dates:
  dueDate: {
    type: Date,
    required: true
  },

  // Late fee:
  lateFee: {
    type: Number,
    default: 0
  },
  lateFeeApplied: {
    type: Boolean,
    default: false
  },

  // Receipt S3 URL:
  receipt: {
    type: String,
    default: null
  },

  // Remarks:
  remarks: {
    type: String,
    default: null
  },

  // Generated by:
  generatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  }
}, { timestamps: true })

export const Fee = mongoose.model(
  'Fee', feeSchema
)